apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zlgtznt1t-python 
  janus-idp.io/tekton: zlgtznt1t-python
  backstage.io/kubernetes-id: zlgtznt1t-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zlgtznt1t-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  